### ISSUE TITLE
버그가 있어여!

### ISSUE THREAD

**Issue by nerogit** [EDCMTV/js_assignment#2]
체크박스눌렀다 뗐다 해보셈ㅋㅋㅋ 
![image](https://cloud.githubusercontent.com/assets/9590242/21289056/240bd2de-c4d6-11e6-9205-86c35e85732c.png)

**Comment by nerogit** [comment]
지우고 다시만들어도 카운팅 제대로 안되고

**Comment by nerogit** [comment]
![image](https://cloud.githubusercontent.com/assets/9590242/21289062/51dffb18-c4d6-11e6-81d5-76fd9ef89629.png)

수정기능도 구현안했네

**Comment by EDCMTV** [comment]
앜
